"""added rag_selected

Revision ID: 0df82af60719
Revises: ab7ae8605fbf
Create Date: 2024-05-26 12:41:22.194023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df82af60719'
down_revision = 'ab7ae8605fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rag_selected', sa.String(length=35), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('rag_selected')

    # ### end Alembic commands ###
