"""add rag_used column

Revision ID: 743a470341d5
Revises: 0df82af60719
Create Date: 2024-06-02 23:43:58.310676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743a470341d5'
down_revision = '0df82af60719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rag_used', sa.String(length=35), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('rag_used')

    # ### end Alembic commands ###
