"""add LLM stuff

Revision ID: 97905c607571
Revises: c34c151c1d7d
Create Date: 2024-05-24 21:04:39.736603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97905c607571'
down_revision = 'c34c151c1d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chatbot', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('embed_model', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('llm_temp', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rag_list', sa.PickleType(), nullable=True))
        batch_op.add_column(sa.Column('chat_history', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('chat_history')
        batch_op.drop_column('rag_list')
        batch_op.drop_column('llm_temp')
        batch_op.drop_column('embed_model')
        batch_op.drop_column('model')
        batch_op.drop_column('chatbot')

    # ### end Alembic commands ###
