"""added api key

Revision ID: ab7ae8605fbf
Revises: 97905c607571
Create Date: 2024-05-25 16:46:24.870410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab7ae8605fbf'
down_revision = '97905c607571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_api_key', sa.String(length=46), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('llm_api_key')

    # ### end Alembic commands ###
