"""added full name, phone, and role

Revision ID: c34c151c1d7d
Revises: cbf35b337542
Create Date: 2024-05-23 22:53:22.622449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c34c151c1d7d'
down_revision = 'cbf35b337542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=64), default='regular', nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.String(length=120), default='', nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('full_name')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
